name: RandomQuotes-build-test

on:
  push:
    branches: 
      - main
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch:

env:
  OCTOPUS_PROJECT_NAME: RandomQuotes
  OCTOPUS_RELEASE_ENVIRONMENT: Development
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUSSERVERAPIKEY }}
  OCTOPUS_HOST: ${{ secrets.OCTOPUSSERVERURL }}

jobs:
  get-release-information:
    runs-on: windows-latest
    outputs:
      OCTOPUS_ENVIRONMENT: ${{ steps.step1.outputs.OctopusEnvironmentName }}
      VERSION: ${{ steps.step1.outputs.OctopusVersionNumber }}
    steps:
      - uses: actions/checkout@v2
      - id: step1
        name: Get Octopus Information
        run: |
          $environmentName = "${env:OCTOPUS_RELEASE_ENVIRONMENT}"
          Write-Host "The environment name is now $environmentName"
          $versionNumber = "1.${env:GITHUB_RUN_NUMBER}"
          Write-Host "The version number is now $versionNumber"

          Write-Host "Setting the Output Variable VERSION to $versionNumber"
          echo "::set-output name=OctopusVersionNumber::$versionNumber"

          Write-Host "Setting the Output Variable OCTOPUS_ENVIRONMENT to $environmentName"
          echo "::set-output name=OctopusEnvironmentName::$environmentName"

        shell: powershell  
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
          mkdir "$GITHUB_WORKSPACE/artifacts/web"
          mkdir "$GITHUB_WORKSPACE/artifacts/database"

      - name: install octopus cli
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
        with:
          version: latest

      - name: restore dependencies for application
        working-directory: src
        run: dotnet restore

      - name: build website
        env:
          VERSION_NUMBER: ${{ needs.get-release-information.outputs.VERSION }}  
        working-directory: src/RandomQuotes
        run: dotnet publish --output "$GITHUB_WORKSPACE/artifacts/web" -c Release --runtime win-x64 --sc false

      - name: package website
        env:
          VERSION_NUMBER: ${{ needs.get-release-information.outputs.VERSION }}  
        run: |
          octo pack --id="RandomQuotes" --format="Zip" --basePath="$GITHUB_WORKSPACE/artifacts/web" --outFolder="$GITHUB_WORKSPACE/artifacts"

      - name: build database
        env:
          VERSION_NUMBER: ${{ needs.get-release-information.outputs.VERSION }}  
        working-directory: src/RandomQuotes.DbUp
        run: dotnet publish --output "$GITHUB_WORKSPACE/artifacts/database" -c Release --runtime win-x64 --sc true --p:PublishSingleFile=true --p:PublishTrimmed=true
      
      - name: package database
        env:
          VERSION_NUMBER: ${{ needs.get-release-information.outputs.VERSION }}  
        run: |
          octo pack --id="RandomQuotes.DbUp" --format="Zip" --basePath="$GITHUB_WORKSPACE/artifacts/database" --outFolder="$GITHUB_WORKSPACE/artifacts"

      - name: push packages to Octopus
        uses: OctopusDeploy/push-package-action@v1.1.1
        with:
          api_key: ${{ env.OCTOPUS_API_KEY }}
          server: ${{ env.OCTOPUS_HOST }}
          packages: "artifacts/RandomQuotes.DbUp.${{ needs.get-release-information.outputs.VERSION }}.zip,artifacts/RandomQuotes.${{ needs.get-release-information.outputs.VERSION }}.zip"
